### ISSUE TITLE
SenseHat.Create not thread safe

### ISSUE THREAD

**Issue by paulspiteri** [emmellsoft/RPi.SenseHat#1]
Hi
I'm not sure how bothered you are about it, but there's a clear race condition in SenseHatFactory.Create()

Avoiding that, is it ok to read from the sensors on any thread?

Thanks!

**Comment by emmellsoft** [comment]
Hi Paul,

Thanks for you feedback!
Yes, I am aware of the race condition in the Create method. I will fix this.

Regarding the rest of the API, it's deliberately not thread-safe to
maximize performance (following the standard of most of the non-static
classes in .NET framework).
So you should avoid calling (for instance) the Update method on the sensors
simultaneously from different threads -- but you *can* call it from any
thread. (But you should be able to access the Readings property without the
need of locks without any problems.)

Thanks for pointing this out -- I will update the [tiny] documentation
regarding this.

/Mattias


2015-10-13 23:36 GMT+02:00 Paul Spiteri <notifications@github.com>:

**Comment by paulspiteri** [comment]
Ok, fantastic.
Thanks for the lib - it's really cool.

**Comment by emmellsoft** [comment]
Hello there!

Sorry about the delay; a whole busy month has passed by. But now I have
gotten some time to fix the race conditions in the SenseHatFactory. In the
end it was a crazy-simple solution, thanks to the inner workings of Task(s).

It's pushed to GitHub and the NuGet package is uploaded (V 1.0.8.0).

Have a nice Sunday evening! :-)
/Mattias


2015-10-15 11:44 GMT+02:00 Paul Spiteri <notifications@github.com>:
