### ISSUE TITLE
RichardsTech.Sensors.SensorException

### ISSUE THREAD

**Issue by luuk777w** [emmellsoft/RPi.SenseHat#10]
Hi,

I sometimes get the following error when trying to run a project:

> Exception thrown: 'RichardsTech.Sensors.SensorException' in System.Private.CoreLib.ni.dll

When this happens I have to restart the Pi, because I cannot run any project on the Pi.
Sometimes I don't get the errors in a while and sometimes I have to restart the Pi each time.
What could be causing this?

**Comment by emmellsoft** [comment]
The SensorException is thrown when there is problems around the communication with the sensor chips. Why this would happen is really hard to say, but given that it gets better after restarting the Pi hints that it is a low-level/hardware issue.

**Comment by luuk777w** [comment]
Yeah, I was thinking that. Is there a way to see what sensor exactly is failing? And if I am not using it I can just ignore the exception. It's quite annoying having to restart the Pi everytime.

**Comment by emmellsoft** [comment]
Make sure that Visual Studio breaks when the exception is thrown; then you can see why that happens in your case. If you check the code you can see that it is thrown in a number of places.

**Comment by luuk777w** [comment]
VS does not break...
I just get the exception in the output log.

**Comment by luuk777w** [comment]
I power my Pi through the USB port of my keyboard.
Could that be an issue?
That I need to power it using the official adapter?
Or can it be that the the CPU gets too hot? (I have no idea)

**Comment by emmellsoft** [comment]
It could be the powering; it's funny, just today I read an article about issues you could have with your Pi, and powering was the first thing. (Second biggest issue is the SD card.) They recommended to get a power supply that could deliver (at least) 2.5 A. Using the output from a computer is not recommended. (I will see if I can find the article; it was some ad on Facebook on my mobile, so it's probably gone...)

**Comment by luuk777w** [comment]
Hmmmmmm.... Okay, will switch to the original powersupply then.

**Comment by luuk777w** [comment]
original powersupply is not the solution.
I did order a new SD card (Samsung microSDHC EVO+ 32 GB) needed a new one anyway.
Will see if that's the problem.
If not, I'm lost...
Will keep you posted.

**Comment by emmellsoft** [comment]
The article (which I of course didn't find again) said that you should stick with the high-end brands of SD cards; like Samsung, Sandisk and Kingston. Also make sure it's fast enough (like class 10).

**Comment by luuk777w** [comment]
I have the original Raspberry Pi SD card. 16gb class 10.

**Comment by luuk777w** [comment]
Okay, turns out, it's not the SD card, nor the power supply. 
Still getting the exceptions, but a lot less frequent. Got only 2 today.
Compaired to a couple days back when I got them almost every third time I deployed my program...
But, I am wondering: Is this even fixable? Or is it purely a hardware issue?

**Comment by luuk777w** [comment]
I don't know why, but i am not getting the exceptions anymore, so I will close this Issue now.
