### ISSUE TITLE
Exception thrown: 'System.IO.FileNotFoundException' in RTIMULibCS.dll

### ISSUE THREAD

**Issue by conekeo** [emmellsoft/RPi.SenseHat#11]
Hi,

I try to run the demo and I got the following error, any idea someone?

Visual Studio 2017
Targer version: Windows 10 version 1803 (10.0; build  17134)
Microsoft.NETCore.UniversalWindowsPlatform v6.1.7
Windows Iot Core 10.0.17134.1
Sandisk  Ultra 16gb  microSDHC class 10.

Error:
```
Exception thrown: 'System.IO.FileNotFoundException' in RTIMULibCS.dll
WinRT information: Slave address was not acknowledged.
Exception thrown: 'RichardsTech.Sensors.SensorException' in RTIMULibCS.dll
Exception thrown: 'RichardsTech.Sensors.SensorException' in System.Private.CoreLib.ni.dll
```

**Comment by emmellsoft** [comment]
Googling `FileNotFoundException "Slave address was not acknowledged"` hints that it's possible a hardware error; something is wrong with the I2C communication. Maybe a faulty SenseHAT?
