### ISSUE TITLE
Migrate project to dotnetcore

### ISSUE THREAD

**Issue by DanielSSilva** [emmellsoft/RPi.SenseHat#12]
There's currently a fork of this project that _supposedly_ works (I wasn't yet able to fully test it). I talked to the owner of the fork and he said that unfortunatelly he can't work on it anymore. He also told me that there was the need to adapt the WiringPi and RaspberryIO libraries to fully support I2C. This means that he had to also fork those projects, change them and do a new build.
Since part of that port is already done, I would suggest to merge both branches and work only on this one (since it's the original). But for that, I would like to have your help, so that we can both see what can be optimized and how so (I have strong c# knowledge, but not familiar with the project).

**Comment by emmellsoft** [comment]
I have pushed a version ported to .NET standard now. :-)

**Comment by DanielSSilva** [comment]
It still has to be ported to the dotnet core in order to run on pi (without mono)

**Comment by emmellsoft** [comment]
Now there is a .NET Core demo!

**Comment by emmellsoft** [comment]
(I will fix the image demos tomorrow)

**Comment by DanielSSilva** [comment]
Awesome! I was able to port to dotnet core and used the raspberryio. Which library you used? I will check it tomorrow when I have the chance.
When I ported, i wasn't able to use the led matrix neither the joystick

**Comment by emmellsoft** [comment]
It turned out that Microsoft is working on a nuget called `System.Device.Gpio`. It's still a pre-release, but it worked fine for the SenseHAT. :-)

**Comment by DanielSSilva** [comment]
Awesome! Does it support I2C as well?

**Comment by emmellsoft** [comment]
Yeps! Everything seems to work. And I just added a simple ImageSerializer to embed images as code to avoid having to load a PNG in runtime.

**Comment by DanielSSilva** [comment]
As a suggestion, the Demos should be moved to a library, since they are shared on both core and uwp versions. If you want I can submit a PR for that (just won't submit know because it seems that you are still working through it)

**Comment by emmellsoft** [comment]
Good idea. I don't have any more changes at the moment, so feel free to submit a PR! :-)

**Comment by DanielSSilva** [comment]
On which OS have you tested? Trying on raspbian i get the error "windows10I2CDevice class is not available on windows" which, as the name implies, is for windows...
I know that the raspberryio library works well with i2c, but methods may differ

**Comment by DanielSSilva** [comment]
Found out that "UnixI2cDevice" exists and it works! Just tested the sprite animation! I will submit the PR when I have WiFi

**Comment by emmellsoft** [comment]
You're right; I've just uploaded a fix for that. Now it chooses between Windows and Linux automatically. :-)
