### ISSUE TITLE
working with Pi3 and the sense hat

### ISSUE THREAD

**Issue by stevendewaele** [emmellsoft/RPi.SenseHat#2]
Is this library tested on a Pi3 and the sensehat?
Can it read all sensors on the board?

**Comment by emmellsoft** [comment]
1. Not by me -- yet.
2. Yes.
:-)

**Comment by FranLsz** [comment]
Hi Mattias, thank you for providing us this library. 

Im thinking to buy a Sense Hat board to my RPi 3, but, first, I want to know if this library works (because I prefer to use Windows 10 IoT) . 
Do you know anyone who tests that?

Regards

**Comment by emmellsoft** [comment]
No, sorry; I haven't got around to try that yet (don't have a RPi 3 either) -- and I don't know if anyone have tried it.

**Comment by emmellsoft** [comment]
It works! I used Windows 10 IoT Core version 10.0.14393.0 and it executed fine on a Raspberry Pi 3.
