### ISSUE TITLE
SensorHat Library is broken with new Windows 10 IoT Core builds

### ISSUE THREAD

**Issue by quadaloop** [emmellsoft/RPi.SenseHat#3]
Starting after update to Windows IoT Core Version 10.0.14366.0 and still with the newest Version 10.0.14376.0 my previously working Demo (and own Application) gets an exception in Method

BootDevice()
on line: I2CSupport.Write(_accelGyroI2CDevice, LSM9DS1Defines.CTRL8, 0x81, "Failed to boot LSM9DS1");

That reads: "The semaphore timeout period has expired.\r\n\r\nAn unexpected error occurred when communicating with the device."

As of now it is not possible for me to make the sensehat run with the library anymore.

I'm Running a "Raspberry Pi 2 Model B"
with the newest IoT Core Build (10.0.14376.0)
and the newest available Library from NuGet (1.0.9) in my own project respectively the demo version from github.

**Comment by emmellsoft** [comment]
I have just confirmed that the code runs fine on both Raspberry Pi 2 and 3 on Windows 10 IoT Core version 10.0.14393.0.
