### ISSUE TITLE
need guidance - namespace name 'I2c' does not exist

### ISSUE THREAD

**Issue by wvmstr** [emmellsoft/RPi.SenseHat#4]
I am on 10.0.14393.67

After a build there are lots of complaints about "the type or namespace name 'I2c does not exist in the namespace 'Windows.Devices".

I have uninstalled Windows Iot Project Templates, and reinstalled them. Still no I2c

**Comment by emmellsoft** [comment]
My guess is that you haven't added the reference "Windows IoT Extensions for the UWP" extension.

Right-click the "References" node in your app (in the Solution Explorer) and choose "Add Reference". Then select "Universal Windows / Extensions" in the left part of the Reference Manager pop-up. There you'll find "Windows IoT Extensions for the UWP". If there are multiple of those; pick the one with the highest version number.

**Comment by wvmstr** [comment]
Thanks for your reply.
"Windows IoT Extensions for the UWP" was indeed missing.
I added version 14393.0.
Same error message after build.
I2c is not available within Windows.Devices.
I had experimented with this same project months ago.  Do not recall any issues with missing references.
Then I got side tracked with other projects for a few months, and apparently my Windows 10 preview was beyond updating. Wiped the entire machine, new Windows 10, new Visual Studio.Everything freshly downloaded.
Anything else I could try?
Robert




Date: Sun, 28 Aug 2016 02:58:41 -0700

**Comment by emmellsoft** [comment]
Hmm... That's really weird. My next suggestion would have been to ensure you have the latest Visual Studio (which ensures that you have the latest .NET framework on your machine).
But having this issue after a newly wiped machine and a freshly installed VS makes no sense. "It should just work".   :-/

I just created a new, blank UWP project to test -- and if you then try to use the "I2cDevice" class you will get the same error ("...the type or namespace name 'I2c does not exist..."). But then if you add the "Windows IoT Extensions for the UWP" extension it resolves without a problem.

Do you get the same problem if you create a blank project (i.e., could it be that your copy of the SenseHat-project is somehow corrupted)?

**Comment by wvmstr** [comment]
Microsoft Visual Studio Community 2015Version 14.0.25425.01 Update 3Microsoft .NET FrameworkVersion 4.6.01586
New blank UWP project, add the reference ok, but still cannot find I2c.

I have posted to the msdn forum, maybe Microsoft will take notice.

Thanks for your help.
Robert


The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
Date: Sun, 28 Aug 2016 05:33:34 -0700

**Comment by emmellsoft** [comment]
Strange to say the least; I really hope it works out for you! Good luck! :-)

**Comment by wvmstr** [comment]
Hey,
Back again. I had been suggested at the msdn forum to reinstall VS2015 and try again. That fixed this problem, and I was able to get your code working.

Now I am working on this project: https://dgkanatsios.com/2016/03/09/raspberry-pi-sense-hat-azure-iot-hub-oh-my/comment-page-1/#comment-265
The last two comments at the bottom of that page are mine.
There seems to be a problem with the SenseHatFactory:
Severity	Code	Description	Project	File	Line	Suppression StateError	CS0117	'SenseHatFactory' does not contain a definition for 'Singleton'	SenseHatIoTHub	C:\Users\Robert\Downloads\Raspberry-master\SenseHatIoTHub\SenseHatIoTHub\MainPage.xaml.cs	36	Active

Severity	Code	Description	Project	File	Line	Suppression StateError	CS0117	'AzureIoTHub' does not contain a definition for 'SendSenseHatDataToCloudAsync'	SenseHatIoTHub	C:\Users\Robert\Downloads\Raspberry-master\SenseHatIoTHub\SenseHatIoTHub\MainPage.xaml.cs	57	Active
I started out with your version 1.0.8 which only errored on SendSenseHatDataToCloudAsync
dgkanatsios suggested I try 1.0.10, which has the two errors above.

Is it possible that version 1.0.9 did have both these two pieces of functionality?
Robertaka wavemaster


Date: Sun, 28 Aug 2016 05:33:34 -0700

**Comment by emmellsoft** [comment]
Great that you finally got it to work!
And congratulations on a nice project! :-)

Yes, I did change the creation of the SenseHat class in version 0.1.0.9.

In version 0.1.0.8 you had to call:
ISenseHat senseHat = await SenseHatFactory.Singleton.GetSenseHat();

In version 0.1.0.9 (and up) you have to call:
ISenseHat senseHat = await SenseHatFactory.GetSenseHat();

So the only change you need to do is remove the part "Singleton" from the call chain.
(The old code had some potential problems with race conditions which could occur if you called the GetSenseHat-method simultaneously from two threads at the same time. That was fixed in version 0.1.0.9.)

**Comment by wvmstr** [comment]
Hey Mattias!


Greetings from the US of A.


My apologies in advance for my ignorance on this subject, it is tough to have to learn UWP coming from the web side of coding.


About a year ago I was successful in getting this<https://dgkanatsios.com/2016/03/09/raspberry-pi-sense-hat-azure-iot-hub-oh-my/comment-page-1/#comment-265> to work, with your help. That is basically temperature, pressure, and humidity from the Senshat to an Azure hub, and into an Azure db. Very recently I have added all the data from the IMU sensor.


I found new work from you here<https://github.com/emmellsoft/RPi.SenseHat/blob/master/RPi.SenseHat/RTIMULibCS/Vector3.cs>.


Is vector3.cs already part of Emmellsoft.IoT.RPi.Sensehat?


Robert


________________________________

**Comment by emmellsoft** [comment]
Hey Robert!
Yes, `Vector3` is in the SenseHAT code (also via the Nuget package).
You'll need a using-statement: `using RichardsTech.Sensors;`, then you can access the `Vector3` class.
:-)
Good luck!
/Mattias

**Comment by wvmstr** [comment]
Is there a description somewhere that explains what it does?
________________________________

**Comment by emmellsoft** [comment]
The `Vector3` is part of the "RTIMULibCS" code library by "RichardsTech" that I helped him convert from C++ to C#.
The original C++ code can be found here: https://github.com/RTIMULib/RTIMULib
Here is the ported C# version: https://github.com/emmellsoft/RTIMULibCS
Please see the original code for more documentation! :-)
/Mattias
