### ISSUE TITLE
Key bouncing

### ISSUE THREAD

**Issue by DreamTimerZ** [emmellsoft/RPi.SenseHat#5]
Thanks for the library, almost everything is working marvelously.

However, I seem to be getting a lot of extraneous key events (key bounce?).  Do I need to de-bounce in my app logic?

FYI, RPi 3, W10IoT: 10.0.14393.0, VS2015, and I'm sampling the key updates based on a timer with a 50ms interval.  I've also tried 500ms and got the same results.

**Comment by emmellsoft** [comment]
Thanks for your report; I will look into this! :-)

**Comment by emmellsoft** [comment]
I've just run the JoystickPixel demo, and there it works fine. (The pixel always jumps one step; never two or more.)

Can you please share some of your code where you update & read the state of the joystick?

Thanks!
/Mattias

**Comment by DreamTimerZ** [comment]
Here's a sample project.  I use a timer instead of the threading mechanism you used in your sample because it's easier to explain (I'm teaching a course about Win10IoT).

[SenseHat-TestApp2.zip](https://github.com/emmellsoft/RPi.SenseHat/files/758926/SenseHat-TestApp2.zip)

**Comment by DreamTimerZ** [comment]
Just another note, I do see key bounces when running the default Joystick test from your repo.

**Comment by DreamTimerZ** [comment]
One more note:  I "fixed" it for my purposes by software "debouncing" essentially saying if the previous call to Joystick.Update() returned true then I ignore subsequent "true" returns until it returns false at least once:


            Boolean oldKSC = keyStateChange;

            keyStateChange = senseHat.Joystick.Update();

            if (keyStateChange && !oldKSC)
                HandleButtons();
