### ISSUE TITLE
Hat Stacking

### ISSUE THREAD

**Issue by CJiwan** [emmellsoft/RPi.SenseHat#6]
Hello,

 On a project under Windows IOT I try to use in the same time the SenseHat and an Adafruit Motor  Hat (Adafruit 2348).
Separately, all works fine but when I try to use the both Hat stacked I have a problem.
  The SenseHat are not find any more.

  At the begining I have try under Linux a Python and I had the same problem.  Adafruit help me with these info : 
The Hat spec requires all boards to have an EEPROM, and the goal is for all Hats to populate the EEPROM with the device tree overlay necessary to make the Hat work.

The problem is that all the EEPROMs have the same I2C address, so if you stack Hats, you get an address conflict. Editing /boot/config.txt so it tells the OS what DTOs to use will solve the problem, as long as the correct DTO already exists in /boot/overlays/

Raspbian has DTOs for all the RasPi Foundation Hats, so it's easy to call them out explicitly.

Can you help me too for windows Iot?

**Comment by emmellsoft** [comment]
Hi,

If you put the SD card having Windows IoT Core installed on in a PC you will find a config.txt in the root. This corresponds to the /boot/config.txt file. (For instance, I had to tweak this file to get my 7" HDMI 1024x600 touch screen to work.)
I have no idea if there is support for 'overlays'...  :-/

**Comment by CJiwan** [comment]
Hi,

  I have edited the config.txt and add this line dtoverlay=rpi-sense at the end.  exactely like on the linux configuration.

  And now all works fine.  

  Thanks for your helop.

**Comment by emmellsoft** [comment]
Wow! Fantastic! Great to know! Thanks!  :-D
